T = {
    "en": {
        "title": "Gabi Knits – knitting chart reader for e-ink and Android",
        "desc": "Gabi Knits opens PDF knitting patterns, finds the chart and guides you row by row. Made for BOOX e-ink, also for Android phones and tablets. No ads.",
        "nav": ("E-ink", "How it works", "Features", "Questions", "Contact"),
        "hero_eyebrow": "Knitting chart reader for Android",
        "hero_title": "Always know which row you’re on.",
        "hero_text": "Open a PDF pattern, tap the chart, and Gabi Knits finds its rows and clearly marks the one you are knitting. One big button takes you to the next row, and your progress saves itself.",
        "soon": "Coming soon to Google Play",
        "hero_trust": ("No account", "No ads", "Works without Internet"),
        "pillars": [
            ("It finds the chart for you", "Tap the chart on the page and the app finds its frame and rows by itself. You only check and confirm."),
            ("Your row, always in sight", "The current row is clearly marked, with its number on both sides. One big “Next row” button, easy to press with one hand."),
            ("Made for e-ink", "Black on white, no animations, large buttons and row numbers – designed for BOOX tablets from the very first version."),
        ],
        "eink_eyebrow": "For BOOX e-ink tablets",
        "eink_title": "Designed for e-ink from day one",
        "eink_text": "Gabi Knits began on a BOOX Note Air, and that is where every version is tested. On e-ink the screen stays calm: black on white, nothing moving and nothing that depends on colour. On phones and regular tablets the same app uses colour and smooth movement.",
        "eink_points": [
            ("A thick frame, not colour", "The current row gets a bold black frame, so it stands out on a black-and-white screen."),
            ("No animations", "Pages and rows change in a single step. Nothing slides or fades on the e-ink screen."),
            ("Large buttons and numbers", "Big row buttons and row numbers you can read from your knitting."),
            ("Tested on BOOX Note Air", "Runs on BOOX tablets with Google Play, in portrait and landscape."),
        ],
        "how_title": "How it works",
        "how_lead": "Three steps from a PDF to your needles.",
        "steps": [
            ("Open your PDF pattern", "Tap “Projects”, then “New project”, and pick the file. The project gets its own name and remembers where you are."),
            ("Tap the chart", "Gabi Knits finds the chart’s frame and rows and asks you to check them. You can adjust the edges by hand."),
            ("Knit row by row", "The current row is clearly marked and the counter shows “Row 14 of 40”. “Next row” moves on, “Previous row” goes back."),
        ],
        "feat_title": "What it can do",
        "feat_lead": "Only what helps you get through the row – nothing that gets in the way.",
        "feats": [
            ("Sequence", "Set the order you knit the charts in, for example Cupcake · Gabi · Cupcake. On the last row, “Next row” moves to the next chart and its page by itself."),
            ("The key at hand", "Mark the pattern key once. It opens over the page with one tap, and your row stays where it was."),
            ("Several charts in one pattern", "Each chart remembers its own row. Switch with the ‹ › arrows on the bar by the row counter – one tap, page uncovered – or with the floating widget."),
            ("Row in the middle of the screen", "The chart moves under a fixed bar, so the row you are knitting stays in the middle of the screen."),
            ("Knitting timer", "See how long a project took. It runs only when you turn it on, also in a project without a chart."),
            ("A guided first project", "On first start, a short tutorial walks you step by step through the practice pattern “Gaba” – Gabi the cat in glasses and a cupcake."),
            ("Progress saves itself", "Each project remembers its page, charts, rows and knitting time. The row history shows your latest moves, and “Back to row 1” starts a chart over."),
            ("Six languages", "English, Polish, German, Norwegian, Danish and Swedish."),
        ],
        "devices_title": "On e-ink, phone and tablet",
        "devices_lead": "One app with a layout for each screen. Portrait or landscape, zoom from 100 to 500% or Auto, and the page can be rotated when a chart lies sideways.",
        "shots": ("BOOX e-ink tablet", "Phone", "Tablet"),
        "alt": {
            "eink": "Gabi Knits on a BOOX e-ink tablet: the Gabi the cat chart from the practice pattern “Gaba”, with the current row in a thick black frame and its number on both sides",
            "phone": "Gabi Knits on a phone: the Gabi the cat chart with the current row under a yellow magnifying bar and large Next row and Previous row buttons",
            "tablet": "Gabi Knits on a tablet: the practice pattern “Gaba” with the cat and cupcake charts and the current row highlighted",
            "step1": "The Projects list with the practice pattern “Gaba” added as a project",
            "step2": "The Gabi the cat chart marked after one tap: lines on the rows and the question how many rows there are",
            "step3": "Knitting the Gabi chart row by row: the current row highlighted and the Next row button below",
        },
        "price_title": "Price",
        "price_lead": "Try everything free for 14 days. Then choose what suits you.",
        "plans": [
            ("Monthly", "€2.99", "per month", True),
            ("Yearly", "€5.99", "per year", True),
            ("Forever", "€14.99", "one-time payment", False),
        ],
        "best": "Best value",
        "trial_yes": "<b>14 days free</b>, then renews automatically unless you cancel.",
        "trial_no": "Pay once, keep it for good.",
        "price_note": "One free trial per Google account. Prices are in euro; Google Play shows the price in your currency. Cancel any time in Google Play.",
        "priv_title": "Your patterns stay with you",
        "priv_points": ("No account", "No ads", "No tracking or analytics", "Works without Internet"),
        "priv_text": "Your PDF patterns, projects and row numbers stay on your device. The app uses the Internet only to handle a purchase and check that you have access – and without a connection you simply keep knitting.",
        "priv_link": "Read the privacy policy",
        "faq_title": "Questions",
        "faq": [
            ("Do I need an account?", "No. There is no sign-up and no login. Purchases go through your Google Play account."),
            ("Does it work without Internet?", "Yes. Reading patterns and knitting never need the Internet. A connection is needed only to buy and, now and then, to confirm your subscription."),
            ("Which devices does it run on?", "Android 8.1 or newer: phones, tablets and BOOX e-ink tablets with Google Play."),
            ("Which patterns work?", "PDF patterns with a chart drawn on a grid. It is tested on dozens of DROPS charts; the app finds the grid and rows itself, and you can correct the edges by hand."),
            ("What can I do without buying?", "Add projects, open patterns, browse the pages and mark charts. Knitting row by row with the marked row needs the free trial or a purchase."),
            ("I have a new phone. Do I pay again?", "No. Install Gabi Knits with the same Google account and tap “Restore purchases”."),
            ("How do I cancel the subscription?", "In Google Play: Payments & subscriptions → Subscriptions. Your projects stay where they are."),
            ("Is there an iPhone or iPad version?", "Not yet – Android comes first."),
        ],
        "cta_title": "Questions or ideas?",
        "cta_text": "Write to Gabi about anything – a pattern that doesn’t work, an idea for the app or a question before launch. Gabi reads every message.",
        "contact_title": "Contact",
        "contact_text": "Questions, ideas, a pattern that doesn’t work? Write to Gabi:",
        "get_title": "Knit your next row with Gabi Knits",
        "get_text": "Free for 14 days, then you choose a plan. No account and no ads.",
        "get_badge": "Get it on Google Play",
        "get_contact": "Questions? Write to Gabi:",
        "video_alt": "Gabi, the cat in glasses, knitting in an armchair in a cosy yarn shop",
        "vat": "VAT ID PL7321956817",
        "privacy": "Privacy policy",
    },
    "pl": {
        "title": "Gabi Knits – schematy dziewiarskie na e-ink i Androida",
        "desc": "Gabi Knits otwiera wzory PDF, sama znajduje schemat i prowadzi rządek po rządku. Stworzona dla e-inku BOOX, działa też na telefonie i tablecie. Bez reklam.",
        "nav": ("E-ink", "Jak to działa", "Funkcje", "Pytania", "Kontakt"),
        "hero_eyebrow": "Czytnik schematów dziewiarskich",
        "hero_title": "Zawsze wiesz, który rządek dziergasz.",
        "hero_text": "Otwórz wzór PDF i dotknij schematu – Gabi Knits sama znajdzie rządki i wyraźnie zaznaczy ten, który właśnie dziergasz. Jeden duży przycisk prowadzi do następnego rządka, a postęp zapisuje się sam.",
        "soon": "Wkrótce w Google Play",
        "hero_trust": ("Bez konta", "Bez reklam", "Działa bez Internetu"),
        "pillars": [
            ("Sama znajduje schemat", "Dotknij schematu na stronie, a aplikacja sama znajdzie jego ramkę i rządki. Ty tylko sprawdzasz i zatwierdzasz."),
            ("Rządek zawsze na widoku", "Bieżący rządek jest wyraźnie zaznaczony, z numerem po obu stronach. Jeden duży przycisk „Następny rządek”, wygodny dla jednej ręki."),
            ("Stworzona dla e-inku", "Czerń na bieli, bez animacji, duże przyciski i numery rządków – projektowana pod tablety BOOX od pierwszej wersji."),
        ],
        "eink_eyebrow": "Dla tabletów e-ink BOOX",
        "eink_title": "Od początku projektowana pod e-ink",
        "eink_text": "Gabi Knits powstała na BOOX Note Air i na nim sprawdzamy każdą wersję. Na e-inku ekran jest spokojny: czerń na bieli, nic się nie przesuwa i nic nie zależy od koloru. Na telefonie i zwykłym tablecie ta sama aplikacja korzysta z koloru i płynnego ruchu.",
        "eink_points": [
            ("Gruba ramka zamiast koloru", "Bieżący rządek otacza wyraźna czarna ramka – dobrze widoczna na czarno-białym ekranie."),
            ("Bez animacji", "Strony i rządki zmieniają się jednym krokiem. Na ekranie e-ink nic nie płynie ani nie przygasa."),
            ("Duże przyciski i numery", "Duże pola rządków i numery rządków czytelne znad robótki."),
            ("Sprawdzona na BOOX Note Air", "Działa na tabletach BOOX ze Sklepem Play, w pionie i w poziomie."),
        ],
        "how_title": "Jak to działa",
        "how_lead": "Trzy kroki od PDF-a do drutów.",
        "steps": [
            ("Otwórz wzór PDF", "Dotknij „Projekty”, potem „Nowy projekt” i wybierz plik. Projekt dostaje własną nazwę i pamięta, w którym miejscu jesteś."),
            ("Dotknij schematu", "Gabi Knits sama znajduje ramkę i rządki schematu, a potem prosi o sprawdzenie. Krawędzie możesz poprawić ręcznie."),
            ("Dziergaj rządek po rządku", "Bieżący rządek jest wyraźnie zaznaczony, a licznik pokazuje „Rządek 14 z 40”. „Następny rządek” prowadzi dalej, „Poprzedni rządek” cofa."),
        ],
        "feat_title": "Co potrafi",
        "feat_lead": "Tylko to, co pomaga przerobić rządek – nic, co by przeszkadzało.",
        "feats": [
            ("Sekwencja", "Ułóż kolejność dziergania schematów, np. Babeczka · Gabi · Babeczka. Na ostatnim rządku „Następny rządek” sam przechodzi do kolejnego schematu i jego strony."),
            ("Legenda pod ręką", "Zaznacz legendę wzoru raz. Otwiera się jednym dotknięciem nad stroną, a rządek zostaje na swoim miejscu."),
            ("Kilka schematów w jednym wzorze", "Każdy schemat pamięta swój rządek. Przełączasz strzałkami ‹ › na pasku przy liczniku – jednym dotknięciem, bez zasłaniania strony – albo pływającym widżetem."),
            ("Rządek na środku ekranu", "Schemat przesuwa się pod stojącym paskiem, więc dziergany rządek zostaje na środku ekranu."),
            ("Licznik czasu", "Sprawdź, ile trwał projekt. Liczy tylko wtedy, gdy go włączysz – także w projekcie bez schematu."),
            ("Pierwszy projekt z przewodnikiem", "Przy pierwszym uruchomieniu samouczek prowadzi krok po kroku przez wzór ćwiczebny „Gaba” – kotkę Gabi w okularach i babeczkę."),
            ("Postęp zapisuje się sam", "Każdy projekt pamięta stronę, schematy, rządki i czas dziergania. Historia rządków pokazuje ostatnie zmiany, a „Wróć do rządka 1” zaczyna schemat od nowa."),
            ("Sześć języków", "Polski, angielski, niemiecki, norweski, duński i szwedzki."),
        ],
        "devices_title": "Na e-inku, telefonie i tablecie",
        "devices_lead": "Jedna aplikacja, osobny układ dla każdego ekranu. Pion albo poziom, powiększenie od 100 do 500% albo Auto, a stronę obrócisz, gdy schemat leży bokiem.",
        "shots": ("Tablet e-ink BOOX", "Telefon", "Tablet"),
        "alt": {
            "eink": "Gabi Knits na tablecie e-ink BOOX: schemat z kotką Gabi ze wzoru ćwiczebnego „Gaba”, bieżący rządek w grubej czarnej ramce, z numerem po obu stronach",
            "phone": "Gabi Knits na telefonie: schemat z kotką Gabi, bieżący rządek pod żółtym paskiem-lupą, poniżej duże przyciski „Następny rządek” i „Poprzedni rządek”",
            "tablet": "Gabi Knits na tablecie: wzór ćwiczebny „Gaba” ze schematami kotki i babeczki, bieżący rządek wyróżniony",
            "step1": "Lista „Projekty” ze wzorem ćwiczebnym „Gaba” dodanym jako projekt",
            "step2": "Schemat z kotką Gabi zaznaczony po jednym dotknięciu: linie na rządkach i pytanie o liczbę rządków",
            "step3": "Dzierganie schematu Gabi rządek po rządku: bieżący rządek wyróżniony, pod spodem przycisk „Następny rządek”",
        },
        "price_title": "Cena",
        "price_lead": "Przez 14 dni wypróbujesz wszystko za darmo. Potem wybierz, co Ci pasuje.",
        "plans": [
            ("Miesięcznie", "6,99 zł", "za miesiąc", True),
            ("Rocznie", "14,99 zł", "za rok", True),
            ("Na zawsze", "39,99 zł", "jednorazowo", False),
        ],
        "best": "Najkorzystniej",
        "trial_yes": "<b>14 dni za darmo</b>, potem odnawia się samo, jeśli nie anulujesz.",
        "trial_no": "Płacisz raz i masz na zawsze.",
        "price_note": "Jedna darmowa próba na konto Google. Subskrypcję anulujesz w każdej chwili w Google Play.",
        "priv_title": "Twoje wzory zostają u Ciebie",
        "priv_points": ("Bez konta", "Bez reklam", "Bez śledzenia i analityki", "Działa bez Internetu"),
        "priv_text": "Wzory PDF, projekty i numery rządków zostają na Twoim urządzeniu. Aplikacja łączy się z Internetem tylko po to, żeby obsłużyć zakup i sprawdzić dostęp – a bez połączenia po prostu dziergasz dalej.",
        "priv_link": "Przeczytaj politykę prywatności",
        "faq_title": "Pytania",
        "faq": [
            ("Czy potrzebuję konta?", "Nie. Nie ma rejestracji ani logowania. Zakup przechodzi przez Twoje konto Google Play."),
            ("Czy działa bez Internetu?", "Tak. Czytanie wzorów i dzierganie nigdy nie wymagają Internetu. Połączenie jest potrzebne tylko do zakupu i od czasu do czasu do potwierdzenia subskrypcji."),
            ("Na jakich urządzeniach działa?", "Na Androidzie 8.1 lub nowszym: na telefonach, tabletach i tabletach e-ink BOOX ze Sklepem Play."),
            ("Jakie wzory się nadają?", "Wzory PDF ze schematem rysowanym na siatce. Aplikacja jest sprawdzona na kilkudziesięciu schematach DROPS; siatkę i rządki znajduje sama, a krawędzie możesz poprawić ręcznie."),
            ("Co mogę zrobić bez zakupu?", "Dodawać projekty, otwierać wzory, przeglądać strony i zaznaczać schematy. Dzierganie rządek po rządku z zaznaczonym rządkiem wymaga darmowej próby albo zakupu."),
            ("Mam nowy telefon. Czy płacę jeszcze raz?", "Nie. Zainstaluj Gabi Knits na tym samym koncie Google i dotknij „Przywróć zakupy”."),
            ("Jak anulować subskrypcję?", "W Google Play: Płatności i subskrypcje → Subskrypcje. Twoje projekty zostają na miejscu."),
            ("Czy jest wersja na iPhone’a albo iPada?", "Jeszcze nie – najpierw Android."),
        ],
        "cta_title": "Masz pytanie albo pomysł?",
        "cta_text": "Napisz do Gabi – o wzorze, który nie działa, o pomyśle na aplikację albo z pytaniem przed premierą. Gabi czyta każdą wiadomość.",
        "contact_title": "Kontakt",
        "contact_text": "Pytanie, pomysł, wzór, który nie działa? Napisz do Gabi:",
        "get_title": "Dziergaj z Gabi Knits",
        "get_text": "14 dni za darmo, potem wybierasz plan. Bez konta i bez reklam.",
        "get_badge": "Pobierz z Google Play",
        "get_contact": "Pytania? Napisz do Gabi:",
        "video_alt": "Kotka Gabi w okularach dzierga w fotelu w przytulnym sklepie z włóczką",
        "vat": "NIP 7321956817",
        "privacy": "Polityka prywatności",
    },
    "de": {
        "title": "Gabi Knits – Strickdiagramme auf E-Ink und Android",
        "desc": "Gabi Knits öffnet PDF-Strickanleitungen, findet das Diagramm und führt dich Reihe für Reihe. Gemacht für BOOX E-Ink, auch für Handy und Tablet.",
        "nav": ("E-Ink", "So geht’s", "Funktionen", "Fragen", "Kontakt"),
        "hero_eyebrow": "Die App für Strickdiagramme",
        "hero_title": "Du weißt immer, welche Reihe dran ist.",
        "hero_text": "Öffne eine PDF-Anleitung und tippe auf das Diagramm – Gabi Knits findet die Reihen selbst und markiert deutlich die, die du gerade strickst. Eine große Taste bringt dich zur nächsten Reihe, und dein Fortschritt speichert sich von allein.",
        "soon": "Bald bei Google Play",
        "hero_trust": ("Kein Konto", "Keine Werbung", "Funktioniert ohne Internet"),
        "pillars": [
            ("Findet das Diagramm selbst", "Tippe auf das Diagramm auf der Seite, und die App findet Rahmen und Reihen von allein. Du prüfst nur und bestätigst."),
            ("Die Reihe immer im Blick", "Die aktuelle Reihe ist deutlich markiert, mit der Nummer auf beiden Seiten. Eine große Taste „Nächste Reihe“, bequem mit einer Hand."),
            ("Gemacht für E-Ink", "Schwarz auf Weiß, keine Animationen, große Tasten und Reihennummern – von der ersten Version an für BOOX-Tablets entworfen."),
        ],
        "eink_eyebrow": "Für BOOX E-Ink-Tablets",
        "eink_title": "Von Anfang an für E-Ink entworfen",
        "eink_text": "Gabi Knits ist auf einem BOOX Note Air entstanden, und dort wird jede Version getestet. Auf E-Ink bleibt der Bildschirm ruhig: Schwarz auf Weiß, nichts bewegt sich, nichts hängt von Farbe ab. Auf Handys und normalen Tablets nutzt dieselbe App Farbe und flüssige Bewegung.",
        "eink_points": [
            ("Dicker Rahmen statt Farbe", "Die aktuelle Reihe bekommt einen kräftigen schwarzen Rahmen – gut zu erkennen auf dem Schwarz-Weiß-Bildschirm."),
            ("Keine Animationen", "Seiten und Reihen wechseln in einem Schritt. Auf dem E-Ink-Bildschirm gleitet und verblasst nichts."),
            ("Große Tasten und Zahlen", "Große Reihentasten und Reihennummern, die du über dem Strickzeug lesen kannst."),
            ("Getestet auf dem BOOX Note Air", "Läuft auf BOOX-Tablets mit Google Play, im Hoch- und im Querformat."),
        ],
        "how_title": "So geht’s",
        "how_lead": "In drei Schritten vom PDF zu den Nadeln.",
        "steps": [
            ("Öffne deine PDF-Anleitung", "Tippe auf „Projekte“, dann auf „Neues Projekt“, und wähle die Datei. Das Projekt bekommt einen eigenen Namen und merkt sich, wo du bist."),
            ("Tippe auf das Diagramm", "Gabi Knits findet Rahmen und Reihen des Diagramms und lässt sie dich kurz prüfen. Die Ränder kannst du von Hand anpassen."),
            ("Stricke Reihe für Reihe", "Die aktuelle Reihe ist deutlich markiert, der Zähler zeigt „Reihe 14 von 40“. „Nächste Reihe“ geht weiter, „Vorherige Reihe“ zurück."),
        ],
        "feat_title": "Was die App kann",
        "feat_lead": "Nur was dir durch die Reihe hilft – nichts, was stört.",
        "feats": [
            ("Abfolge", "Lege fest, in welcher Reihenfolge du die Diagramme strickst, zum Beispiel Muffin · Gabi · Muffin. In der letzten Reihe wechselt „Nächste Reihe“ von selbst zum nächsten Diagramm und seiner Seite."),
            ("Die Legende griffbereit", "Markiere die Legende der Anleitung einmal. Sie öffnet sich mit einem Tippen über der Seite, und deine Reihe bleibt, wo sie ist."),
            ("Mehrere Diagramme in einer Anleitung", "Jedes Diagramm merkt sich seine Reihe. Du wechselst mit den Pfeilen ‹ › in der Leiste am Reihenzähler – ein Tippen, die Seite bleibt frei – oder mit dem schwebenden Widget."),
            ("Reihe in der Bildschirmmitte", "Das Diagramm bewegt sich unter einer festen Leiste, so bleibt die Reihe, die du strickst, in der Mitte des Bildschirms."),
            ("Strickzeit", "Sieh, wie lange ein Projekt gedauert hat. Die Uhr läuft nur, wenn du sie einschaltest – auch bei Projekten ohne Diagramm."),
            ("Geführt durchs erste Projekt", "Beim ersten Start führt dich ein kurzes Tutorial Schritt für Schritt durch die Übungsanleitung „Gaba“ – die Katze Gabi mit Brille und einen Muffin."),
            ("Fortschritt speichert sich selbst", "Jedes Projekt merkt sich Seite, Diagramme, Reihen und Strickzeit. Der Reihenverlauf zeigt deine letzten Schritte, und „Zurück zu Reihe 1“ beginnt ein Diagramm neu."),
            ("Sechs Sprachen", "Deutsch, Englisch, Polnisch, Norwegisch, Dänisch und Schwedisch."),
        ],
        "devices_title": "Auf E-Ink, Handy und Tablet",
        "devices_lead": "Eine App mit eigenem Layout für jeden Bildschirm. Hoch- oder Querformat, Zoom von 100 bis 500 % oder Auto, und die Seite lässt sich drehen, wenn ein Diagramm quer liegt.",
        "shots": ("BOOX E-Ink-Tablet", "Handy", "Tablet"),
        "alt": {
            "eink": "Gabi Knits auf einem BOOX E-Ink-Tablet: das Diagramm mit der Katze Gabi aus der Übungsanleitung „Gaba“, die aktuelle Reihe in einem dicken schwarzen Rahmen, die Nummer auf beiden Seiten",
            "phone": "Gabi Knits auf dem Handy: das Diagramm mit der Katze Gabi, die aktuelle Reihe unter einer gelben Lupenleiste, darunter große Tasten „Nächste Reihe“ und „Vorherige Reihe“",
            "tablet": "Gabi Knits auf dem Tablet: die Übungsanleitung „Gaba“ mit den Diagrammen Katze und Muffin, die aktuelle Reihe hervorgehoben",
            "step1": "Die Liste „Projekte“ mit der Übungsanleitung „Gaba“ als Projekt",
            "step2": "Das Diagramm mit der Katze Gabi nach einem Tippen markiert: Linien auf den Reihen und die Frage nach der Zahl der Reihen",
            "step3": "Das Diagramm Gabi Reihe für Reihe stricken: die aktuelle Reihe hervorgehoben, darunter die Taste „Nächste Reihe“",
        },
        "price_title": "Preis",
        "price_lead": "Probiere 14 Tage lang alles kostenlos aus. Dann wähle, was zu dir passt.",
        "plans": [
            ("Monatlich", "2,99 €", "pro Monat", True),
            ("Jährlich", "5,99 €", "pro Jahr", True),
            ("Für immer", "14,99 €", "einmalig", False),
        ],
        "best": "Am günstigsten",
        "trial_yes": "<b>14 Tage kostenlos</b>, danach automatische Verlängerung, wenn du nicht kündigst.",
        "trial_no": "Einmal zahlen, für immer behalten.",
        "price_note": "Ein kostenloser Test pro Google-Konto. Preise in Euro; Google Play zeigt den Preis in deiner Währung. Jederzeit in Google Play kündbar.",
        "priv_title": "Deine Anleitungen bleiben bei dir",
        "priv_points": ("Kein Konto", "Keine Werbung", "Kein Tracking, keine Analyse", "Funktioniert ohne Internet"),
        "priv_text": "Deine PDF-Anleitungen, Projekte und Reihennummern bleiben auf deinem Gerät. Die App nutzt das Internet nur, um einen Kauf abzuwickeln und deinen Zugang zu prüfen – ohne Verbindung strickst du einfach weiter.",
        "priv_link": "Datenschutzerklärung lesen",
        "faq_title": "Fragen",
        "faq": [
            ("Brauche ich ein Konto?", "Nein. Keine Registrierung, keine Anmeldung. Käufe laufen über dein Google-Play-Konto."),
            ("Funktioniert die App ohne Internet?", "Ja. Anleitungen lesen und stricken brauchen nie Internet. Eine Verbindung ist nur zum Kaufen und ab und zu zur Bestätigung des Abos nötig."),
            ("Auf welchen Geräten läuft sie?", "Android 8.1 oder neuer: Handys, Tablets und BOOX E-Ink-Tablets mit Google Play."),
            ("Welche Anleitungen passen?", "PDF-Anleitungen mit einem Diagramm auf einem Raster. Getestet mit Dutzenden DROPS-Diagrammen; Raster und Reihen findet die App selbst, die Ränder kannst du von Hand korrigieren."),
            ("Was geht ohne Kauf?", "Projekte anlegen, Anleitungen öffnen, Seiten durchblättern und Diagramme markieren. Reihe für Reihe mit markierter Reihe stricken erfordert den kostenlosen Test oder einen Kauf."),
            ("Ich habe ein neues Handy. Zahle ich noch einmal?", "Nein. Installiere Gabi Knits mit demselben Google-Konto und tippe auf „Käufe wiederherstellen“."),
            ("Wie kündige ich das Abo?", "In Google Play: Zahlungen und Abos → Abos. Deine Projekte bleiben, wo sie sind."),
            ("Gibt es eine Version für iPhone oder iPad?", "Noch nicht – zuerst kommt Android."),
        ],
        "cta_title": "Fragen oder Ideen?",
        "cta_text": "Schreib Gabi – zu einer Anleitung, die nicht funktioniert, zu einer Idee für die App oder mit einer Frage vor dem Start. Gabi liest jede Nachricht.",
        "contact_title": "Kontakt",
        "contact_text": "Fragen, Ideen, eine Anleitung, die nicht funktioniert? Schreib Gabi:",
        "get_title": "Stricke mit Gabi Knits",
        "get_text": "14 Tage kostenlos, danach wählst du ein Abo. Kein Konto, keine Werbung.",
        "get_badge": "Jetzt bei Google Play",
        "get_contact": "Fragen? Schreib Gabi:",
        "video_alt": "Die Katze Gabi mit Brille strickt im Sessel in einem gemütlichen Wollladen",
        "vat": "USt-IdNr. PL7321956817",
        "privacy": "Datenschutzerklärung",
    },
    "nb": {
        "title": "Gabi Knits – strikkediagrammer på e-ink og Android",
        "desc": "Gabi Knits åpner PDF-strikkeoppskrifter, finner diagrammet og leder deg rad for rad. Laget for BOOX e-ink, også for telefon og nettbrett. Ingen reklame.",
        "nav": ("E-ink", "Slik virker det", "Funksjoner", "Spørsmål", "Kontakt"),
        "hero_eyebrow": "Diagramleser for strikking",
        "hero_title": "Du vet alltid hvilken rad du er på.",
        "hero_text": "Åpne en PDF-oppskrift og trykk på diagrammet – Gabi Knits finner radene selv og markerer tydelig den du strikker nå. Én stor knapp tar deg til neste rad, og fremdriften lagres av seg selv.",
        "soon": "Kommer snart på Google Play",
        "hero_trust": ("Ingen konto", "Ingen reklame", "Virker uten internett"),
        "pillars": [
            ("Finner diagrammet selv", "Trykk på diagrammet på siden, så finner appen rammen og radene selv. Du sjekker bare og bekrefter."),
            ("Raden alltid i syne", "Gjeldende rad er tydelig markert, med nummeret på begge sider. Én stor «Neste rad»-knapp, lett å trykke på med én hånd."),
            ("Laget for e-ink", "Svart på hvitt, ingen animasjoner, store knapper og radnumre – utformet for BOOX-nettbrett fra første versjon."),
        ],
        "eink_eyebrow": "For BOOX e-ink-nettbrett",
        "eink_title": "Utformet for e-ink fra starten",
        "eink_text": "Gabi Knits ble til på en BOOX Note Air, og der blir hver versjon testet. På e-ink er skjermen rolig: svart på hvitt, ingenting som beveger seg og ingenting som avhenger av farger. På telefoner og vanlige nettbrett bruker den samme appen farger og jevn bevegelse.",
        "eink_points": [
            ("Tykk ramme i stedet for farge", "Gjeldende rad får en kraftig svart ramme – tydelig på en svart-hvitt-skjerm."),
            ("Ingen animasjoner", "Sider og rader skifter i ett steg. Ingenting glir eller toner ut på e-ink-skjermen."),
            ("Store knapper og tall", "Store radknapper og radnumre du kan lese over strikketøyet."),
            ("Testet på BOOX Note Air", "Virker på BOOX-nettbrett med Google Play, både stående og liggende."),
        ],
        "how_title": "Slik virker det",
        "how_lead": "Tre trinn fra PDF til pinnene.",
        "steps": [
            ("Åpne PDF-oppskriften", "Trykk på «Prosjekter», så «Nytt prosjekt», og velg filen. Prosjektet får sitt eget navn og husker hvor du er."),
            ("Trykk på diagrammet", "Gabi Knits finner rammen og radene i diagrammet og ber deg sjekke dem. Kantene kan du justere for hånd."),
            ("Strikk rad for rad", "Gjeldende rad er tydelig markert, og telleren viser «Rad 14 av 40». «Neste rad» går videre, «Forrige rad» går tilbake."),
        ],
        "feat_title": "Hva appen kan",
        "feat_lead": "Bare det som hjelper deg gjennom raden – ingenting som er i veien.",
        "feats": [
            ("Sekvens", "Bestem rekkefølgen du strikker diagrammene i, for eksempel Muffins · Gabi · Muffins. På siste rad går «Neste rad» selv videre til neste diagram og siden det står på."),
            ("Tegnforklaringen for hånden", "Merk tegnforklaringen i oppskriften én gang. Den åpnes med ett trykk over siden, og raden din blir der den er."),
            ("Flere diagrammer i én oppskrift", "Hvert diagram husker sin rad. Du bytter med pilene ‹ › på stripen ved radtelleren – ett trykk, og siden er fri – eller med den flytende widgeten."),
            ("Raden midt på skjermen", "Diagrammet flytter seg under en fast stripe, så raden du strikker, blir værende midt på skjermen."),
            ("Strikketid", "Se hvor lang tid et prosjekt tok. Klokken går bare når du slår den på – også i prosjekter uten diagram."),
            ("Første prosjekt med veiledning", "Ved første oppstart leder en kort veiledning deg steg for steg gjennom øvingsoppskriften «Gaba» – katten Gabi med briller og en muffins."),
            ("Fremdriften lagres av seg selv", "Hvert prosjekt husker side, diagrammer, rader og strikketid. Radhistorikken viser de siste flyttene, og «Tilbake til rad 1» starter et diagram på nytt."),
            ("Seks språk", "Norsk, engelsk, polsk, tysk, dansk og svensk."),
        ],
        "devices_title": "På e-ink, telefon og nettbrett",
        "devices_lead": "Én app med eget oppsett for hver skjerm. Stående eller liggende, zoom fra 100 til 500 % eller Auto, og siden kan roteres når et diagram ligger på tvers.",
        "shots": ("BOOX e-ink-nettbrett", "Telefon", "Nettbrett"),
        "alt": {
            "eink": "Gabi Knits på et BOOX e-ink-nettbrett: diagrammet med katten Gabi fra øvingsoppskriften «Gaba», gjeldende rad i en tykk svart ramme med nummeret på begge sider",
            "phone": "Gabi Knits på telefon: diagrammet med katten Gabi, gjeldende rad under en gul lupestripe og store knapper for «Neste rad» og «Forrige rad»",
            "tablet": "Gabi Knits på nettbrett: øvingsoppskriften «Gaba» med diagrammene katt og muffins, gjeldende rad uthevet",
            "step1": "Listen «Prosjekter» med øvingsoppskriften «Gaba» lagt til som prosjekt",
            "step2": "Diagrammet med katten Gabi merket etter ett trykk: linjer på radene og spørsmålet om hvor mange rader det er",
            "step3": "Gabi-diagrammet strikkes rad for rad: gjeldende rad uthevet og knappen «Neste rad» under",
        },
        "price_title": "Pris",
        "price_lead": "Prøv alt gratis i 14 dager. Velg så det som passer deg.",
        "plans": [
            ("Månedlig", "2,99 €", "per måned", True),
            ("Årlig", "5,99 €", "per år", True),
            ("For alltid", "14,99 €", "engangsbetaling", False),
        ],
        "best": "Mest lønnsomt",
        "trial_yes": "<b>14 dager gratis</b>, fornyes deretter automatisk hvis du ikke sier opp.",
        "trial_no": "Betal én gang, behold den for alltid.",
        "price_note": "Én gratis prøveperiode per Google-konto. Prisene er i euro; Google Play viser prisen i din valuta. Si opp når som helst i Google Play.",
        "priv_title": "Oppskriftene dine blir hos deg",
        "priv_points": ("Ingen konto", "Ingen reklame", "Ingen sporing eller analyse", "Virker uten internett"),
        "priv_text": "PDF-oppskriftene, prosjektene og radnumrene dine blir på enheten din. Appen bruker internett bare til å gjennomføre et kjøp og sjekke at du har tilgang – uten tilkobling strikker du bare videre.",
        "priv_link": "Les personvernerklæringen",
        "faq_title": "Spørsmål",
        "faq": [
            ("Trenger jeg en konto?", "Nei. Ingen registrering og ingen innlogging. Kjøp går gjennom Google Play-kontoen din."),
            ("Virker appen uten internett?", "Ja. Å lese oppskrifter og strikke krever aldri internett. Du trenger tilkobling bare for å kjøpe og av og til for å bekrefte abonnementet."),
            ("Hvilke enheter virker den på?", "Android 8.1 eller nyere: telefoner, nettbrett og BOOX e-ink-nettbrett med Google Play."),
            ("Hvilke oppskrifter passer?", "PDF-oppskrifter med diagram på rutenett. Testet på dusinvis av DROPS-diagrammer; appen finner rutenettet og radene selv, og kantene kan du rette for hånd."),
            ("Hva kan jeg gjøre uten å kjøpe?", "Legge til prosjekter, åpne oppskrifter, bla i sidene og merke diagrammer. Å strikke rad for rad med markert rad krever gratis prøveperiode eller kjøp."),
            ("Jeg har ny telefon. Betaler jeg igjen?", "Nei. Installer Gabi Knits med samme Google-konto og trykk på «Gjenopprett kjøp»."),
            ("Hvordan sier jeg opp abonnementet?", "I Google Play: Betalinger og abonnementer → Abonnementer. Prosjektene dine blir der de er."),
            ("Finnes det en versjon for iPhone eller iPad?", "Ikke ennå – Android kommer først."),
        ],
        "cta_title": "Spørsmål eller ideer?",
        "cta_text": "Skriv til Gabi – om en oppskrift som ikke virker, en idé til appen eller et spørsmål før lanseringen. Gabi leser hver melding.",
        "contact_title": "Kontakt",
        "contact_text": "Spørsmål, ideer, en oppskrift som ikke virker? Skriv til Gabi:",
        "get_title": "Strikk med Gabi Knits",
        "get_text": "14 dager gratis, deretter velger du en plan. Ingen konto og ingen reklame.",
        "get_badge": "Last ned på Google Play",
        "get_contact": "Spørsmål? Skriv til Gabi:",
        "video_alt": "Katten Gabi med briller strikker i en lenestol i en koselig garnbutikk",
        "vat": "MVA-nr. PL7321956817",
        "privacy": "Personvernerklæring",
    },
    "da": {
        "title": "Gabi Knits – strikkediagrammer på e-ink og Android",
        "desc": "Gabi Knits åbner PDF-strikkeopskrifter, finder diagrammet og fører dig række for række. Lavet til BOOX e-ink, også til telefon og tablet. Ingen reklamer.",
        "nav": ("E-ink", "Sådan virker det", "Funktioner", "Spørgsmål", "Kontakt"),
        "hero_eyebrow": "Diagramlæser til strikning",
        "hero_title": "Du ved altid, hvilken række du er nået til.",
        "hero_text": "Åbn en PDF-opskrift og tryk på diagrammet – Gabi Knits finder selv rækkerne og markerer tydeligt den, du strikker nu. Én stor knap fører dig til næste række, og dit fremskridt gemmes af sig selv.",
        "soon": "Kommer snart på Google Play",
        "hero_trust": ("Ingen konto", "Ingen reklamer", "Virker uden internet"),
        "pillars": [
            ("Finder selv diagrammet", "Tryk på diagrammet på siden, så finder appen selv rammen og rækkerne. Du tjekker bare og bekræfter."),
            ("Rækken altid for øje", "Den aktuelle række er tydeligt markeret, med nummeret i begge sider. Én stor »Næste række«-knap, nem at trykke på med én hånd."),
            ("Lavet til e-ink", "Sort på hvidt, ingen animationer, store knapper og rækkenumre – designet til BOOX-tablets fra første version."),
        ],
        "eink_eyebrow": "Til BOOX e-ink-tablets",
        "eink_title": "Designet til e-ink fra begyndelsen",
        "eink_text": "Gabi Knits blev til på en BOOX Note Air, og det er der, hver version bliver testet. På e-ink er skærmen rolig: sort på hvidt, intet der bevæger sig, og intet der afhænger af farver. På telefoner og almindelige tablets bruger den samme app farver og glidende bevægelse.",
        "eink_points": [
            ("Tyk ramme i stedet for farve", "Den aktuelle række får en kraftig sort ramme – tydelig på en sort-hvid skærm."),
            ("Ingen animationer", "Sider og rækker skifter i ét trin. Intet glider eller toner ud på e-ink-skærmen."),
            ("Store knapper og tal", "Store rækkeknapper og rækkenumre, du kan læse over strikketøjet."),
            ("Testet på BOOX Note Air", "Virker på BOOX-tablets med Google Play, både på højkant og på langs."),
        ],
        "how_title": "Sådan virker det",
        "how_lead": "Tre trin fra PDF til pindene.",
        "steps": [
            ("Åbn PDF-opskriften", "Tryk på »Projekter«, så »Nyt projekt«, og vælg filen. Projektet får sit eget navn og husker, hvor du er."),
            ("Tryk på diagrammet", "Gabi Knits finder diagrammets ramme og rækker og beder dig tjekke dem. Kanterne kan du justere i hånden."),
            ("Strik række for række", "Den aktuelle række er tydeligt markeret, og tælleren viser »Række 14 af 40«. »Næste række« går videre, »Forrige række« går tilbage."),
        ],
        "feat_title": "Hvad appen kan",
        "feat_lead": "Kun det, der hjælper dig gennem rækken – intet, der er i vejen.",
        "feats": [
            ("Sekvens", "Bestem rækkefølgen, du strikker diagrammerne i, for eksempel Muffin · Gabi · Muffin. På sidste række går »Næste række« selv videre til næste diagram og dets side."),
            ("Symbolforklaringen ved hånden", "Markér opskriftens symbolforklaring én gang. Den åbner med ét tryk over siden, og din række bliver, hvor den er."),
            ("Flere diagrammer i én opskrift", "Hvert diagram husker sin række. Du skifter med pilene ‹ › på bjælken ved rækketælleren – ét tryk, og siden er fri – eller med den flydende widget."),
            ("Rækken midt på skærmen", "Diagrammet flytter sig under en fast bjælke, så den række, du strikker, bliver midt på skærmen."),
            ("Strikketid", "Se, hvor lang tid et projekt tog. Uret går kun, når du slår det til – også i projekter uden diagram."),
            ("Første projekt med vejledning", "Ved første start fører en kort vejledning dig trin for trin gennem øveopskriften »Gaba« – katten Gabi med briller og en muffin."),
            ("Fremskridtet gemmes af sig selv", "Hvert projekt husker side, diagrammer, rækker og strikketid. Rækkehistorikken viser de seneste skift, og »Tilbage til række 1« starter et diagram forfra."),
            ("Seks sprog", "Dansk, engelsk, polsk, tysk, norsk og svensk."),
        ],
        "devices_title": "På e-ink, telefon og tablet",
        "devices_lead": "Én app med eget layout til hver skærm. Højkant eller på langs, zoom fra 100 til 500 % eller Auto, og siden kan drejes, når et diagram ligger på tværs.",
        "shots": ("BOOX e-ink-tablet", "Telefon", "Tablet"),
        "alt": {
            "eink": "Gabi Knits på en BOOX e-ink-tablet: diagrammet med katten Gabi fra øveopskriften »Gaba«, den aktuelle række i en tyk sort ramme med nummeret i begge sider",
            "phone": "Gabi Knits på telefon: diagrammet med katten Gabi, den aktuelle række under en gul lupbjælke og store knapper til »Næste række« og »Forrige række«",
            "tablet": "Gabi Knits på tablet: øveopskriften »Gaba« med diagrammerne kat og muffin, den aktuelle række fremhævet",
            "step1": "Listen »Projekter« med øveopskriften »Gaba« tilføjet som projekt",
            "step2": "Diagrammet med katten Gabi markeret efter ét tryk: linjer på rækkerne og spørgsmålet om, hvor mange rækker der er",
            "step3": "Gabi-diagrammet strikkes række for række: den aktuelle række fremhævet og knappen »Næste række« nedenunder",
        },
        "price_title": "Pris",
        "price_lead": "Prøv alt gratis i 14 dage. Vælg så det, der passer dig.",
        "plans": [
            ("Månedlig", "2,99 €", "pr. måned", True),
            ("Årlig", "5,99 €", "pr. år", True),
            ("For altid", "14,99 €", "engangsbetaling", False),
        ],
        "best": "Bedst værdi",
        "trial_yes": "<b>14 dage gratis</b>, fornyes derefter automatisk, medmindre du opsiger.",
        "trial_no": "Betal én gang, behold den for altid.",
        "price_note": "Én gratis prøveperiode pr. Google-konto. Priserne er i euro; Google Play viser prisen i din valuta. Opsig når som helst i Google Play.",
        "priv_title": "Dine opskrifter bliver hos dig",
        "priv_points": ("Ingen konto", "Ingen reklamer", "Ingen sporing eller analyse", "Virker uden internet"),
        "priv_text": "Dine PDF-opskrifter, projekter og rækkenumre bliver på din enhed. Appen bruger kun internettet til at gennemføre et køb og kontrollere, at du har adgang – uden forbindelse strikker du bare videre.",
        "priv_link": "Læs privatlivspolitikken",
        "faq_title": "Spørgsmål",
        "faq": [
            ("Skal jeg have en konto?", "Nej. Ingen oprettelse og intet login. Køb går gennem din Google Play-konto."),
            ("Virker appen uden internet?", "Ja. At læse opskrifter og strikke kræver aldrig internet. Forbindelse er kun nødvendig for at købe og en gang imellem for at bekræfte abonnementet."),
            ("Hvilke enheder virker den på?", "Android 8.1 eller nyere: telefoner, tablets og BOOX e-ink-tablets med Google Play."),
            ("Hvilke opskrifter passer?", "PDF-opskrifter med et diagram på et gitter. Testet på snesevis af DROPS-diagrammer; appen finder selv gitteret og rækkerne, og kanterne kan du rette i hånden."),
            ("Hvad kan jeg uden at købe?", "Tilføje projekter, åbne opskrifter, bladre i siderne og markere diagrammer. At strikke række for række med markeret række kræver den gratis prøveperiode eller et køb."),
            ("Jeg har en ny telefon. Betaler jeg igen?", "Nej. Installer Gabi Knits med samme Google-konto og tryk på »Gendan køb«."),
            ("Hvordan opsiger jeg abonnementet?", "I Google Play: Betalinger og abonnementer → Abonnementer. Dine projekter bliver, hvor de er."),
            ("Findes der en version til iPhone eller iPad?", "Ikke endnu – Android kommer først."),
        ],
        "cta_title": "Spørgsmål eller idéer?",
        "cta_text": "Skriv til Gabi – om en opskrift, der ikke virker, en idé til appen eller et spørgsmål før lanceringen. Gabi læser hver besked.",
        "contact_title": "Kontakt",
        "contact_text": "Spørgsmål, idéer, en opskrift, der ikke virker? Skriv til Gabi:",
        "get_title": "Strik med Gabi Knits",
        "get_text": "14 dage gratis, derefter vælger du en plan. Ingen konto og ingen reklamer.",
        "get_badge": "Hent den i Google Play",
        "get_contact": "Spørgsmål? Skriv til Gabi:",
        "video_alt": "Katten Gabi med briller strikker i en lænestol i en hyggelig garnbutik",
        "vat": "Moms-nr. PL7321956817",
        "privacy": "Privatlivspolitik",
    },
    "sv": {
        "title": "Gabi Knits – stickdiagram på e-ink och Android",
        "desc": "Gabi Knits öppnar stickmönster i PDF, hittar diagrammet och guidar dig varv för varv. Gjord för BOOX e-ink, även för telefon och surfplatta. Ingen reklam.",
        "nav": ("E-ink", "Så fungerar det", "Funktioner", "Frågor", "Kontakt"),
        "hero_eyebrow": "Diagramläsare för stickning",
        "hero_title": "Du vet alltid vilket varv du är på.",
        "hero_text": "Öppna ett PDF-mönster och tryck på diagrammet – Gabi Knits hittar själv varven och markerar tydligt det du stickar nu. En stor knapp tar dig till nästa varv, och framstegen sparas automatiskt.",
        "soon": "Kommer snart till Google Play",
        "hero_trust": ("Inget konto", "Ingen reklam", "Fungerar utan internet"),
        "pillars": [
            ("Hittar diagrammet själv", "Tryck på diagrammet på sidan, så hittar appen själv ramen och varven. Du kontrollerar bara och bekräftar."),
            ("Varvet alltid i sikte", "Det aktuella varvet är tydligt markerat, med numret på båda sidor. En stor knapp ”Nästa varv”, lätt att trycka på med en hand."),
            ("Gjord för e-ink", "Svart på vitt, inga animationer, stora knappar och varvnummer – utformad för BOOX-plattor från första versionen."),
        ],
        "eink_eyebrow": "För BOOX e-ink-plattor",
        "eink_title": "Utformad för e-ink från början",
        "eink_text": "Gabi Knits kom till på en BOOX Note Air, och där testas varje version. På e-ink är skärmen lugn: svart på vitt, inget som rör sig och inget som hänger på färg. På telefoner och vanliga surfplattor använder samma app färg och mjuka rörelser.",
        "eink_points": [
            ("Tjock ram i stället för färg", "Det aktuella varvet får en kraftig svart ram – tydlig på en svartvit skärm."),
            ("Inga animationer", "Sidor och varv byts i ett steg. Inget glider eller tonar ut på e-ink-skärmen."),
            ("Stora knappar och siffror", "Stora varvknappar och varvnummer som du kan läsa ovanför stickningen."),
            ("Testad på BOOX Note Air", "Fungerar på BOOX-plattor med Google Play, både stående och liggande."),
        ],
        "how_title": "Så fungerar det",
        "how_lead": "Tre steg från PDF till stickorna.",
        "steps": [
            ("Öppna PDF-mönstret", "Tryck på ”Projekt”, sedan ”Nytt projekt”, och välj filen. Projektet får ett eget namn och minns var du är."),
            ("Tryck på diagrammet", "Gabi Knits hittar diagrammets ram och varv och ber dig kontrollera dem. Kanterna kan du justera för hand."),
            ("Sticka varv för varv", "Det aktuella varvet är tydligt markerat, och räknaren visar ”Varv 14 av 40”. ”Nästa varv” går vidare, ”Föregående varv” går tillbaka."),
        ],
        "feat_title": "Vad appen kan",
        "feat_lead": "Bara det som hjälper dig genom varvet – inget som är i vägen.",
        "feats": [
            ("Sekvens", "Bestäm i vilken ordning du stickar diagrammen, till exempel Muffin · Gabi · Muffin. På sista varvet går ”Nästa varv” själv vidare till nästa diagram och dess sida."),
            ("Teckenförklaringen till hands", "Markera mönstrets teckenförklaring en gång. Den öppnas med ett tryck över sidan, och ditt varv stannar där det är."),
            ("Flera diagram i ett mönster", "Varje diagram minns sitt varv. Du byter med pilarna ‹ › på listen vid varvräknaren – ett tryck, och sidan är fri – eller med den flytande widgeten."),
            ("Varvet mitt på skärmen", "Diagrammet flyttar sig under en fast list, så varvet du stickar stannar mitt på skärmen."),
            ("Sticktid", "Se hur lång tid ett projekt tog. Klockan går bara när du slår på den – även i projekt utan diagram."),
            ("Första projektet med handledning", "Vid första starten guidar en kort handledning dig steg för steg genom övningsmönstret ”Gaba” – katten Gabi med glasögon och en muffin."),
            ("Framstegen sparas automatiskt", "Varje projekt minns sida, diagram, varv och sticktid. Varvhistoriken visar de senaste flyttarna, och ”Tillbaka till varv 1” börjar om ett diagram."),
            ("Sex språk", "Svenska, engelska, polska, tyska, norska och danska."),
        ],
        "devices_title": "På e-ink, telefon och surfplatta",
        "devices_lead": "En app med egen layout för varje skärm. Stående eller liggande, zoom från 100 till 500 % eller Auto, och sidan kan vridas när ett diagram ligger på tvären.",
        "shots": ("BOOX e-ink-platta", "Telefon", "Surfplatta"),
        "alt": {
            "eink": "Gabi Knits på en BOOX e-ink-platta: diagrammet med katten Gabi från övningsmönstret ”Gaba”, det aktuella varvet i en tjock svart ram med numret på båda sidor",
            "phone": "Gabi Knits på telefon: diagrammet med katten Gabi, det aktuella varvet under en gul förstoringslist och stora knappar för ”Nästa varv” och ”Föregående varv”",
            "tablet": "Gabi Knits på surfplatta: övningsmönstret ”Gaba” med diagrammen katt och muffin, det aktuella varvet markerat",
            "step1": "Listan ”Projekt” med övningsmönstret ”Gaba” tillagt som projekt",
            "step2": "Diagrammet med katten Gabi markerat efter ett tryck: linjer på varven och frågan om hur många varv det är",
            "step3": "Gabi-diagrammet stickas varv för varv: det aktuella varvet markerat och knappen ”Nästa varv” under",
        },
        "price_title": "Pris",
        "price_lead": "Prova allt gratis i 14 dagar. Välj sedan det som passar dig.",
        "plans": [
            ("Månadsvis", "2,99 €", "per månad", True),
            ("Årsvis", "5,99 €", "per år", True),
            ("För alltid", "14,99 €", "engångsbetalning", False),
        ],
        "best": "Mest prisvärd",
        "trial_yes": "<b>14 dagar gratis</b>, förnyas sedan automatiskt om du inte säger upp.",
        "trial_no": "Betala en gång, behåll den för alltid.",
        "price_note": "En gratis provperiod per Google-konto. Priserna är i euro; Google Play visar priset i din valuta. Säg upp när som helst i Google Play.",
        "priv_title": "Dina mönster stannar hos dig",
        "priv_points": ("Inget konto", "Ingen reklam", "Ingen spårning eller analys", "Fungerar utan internet"),
        "priv_text": "Dina PDF-mönster, projekt och varvnummer stannar på din enhet. Appen använder internet bara för att genomföra ett köp och kontrollera att du har åtkomst – utan anslutning stickar du bara vidare.",
        "priv_link": "Läs integritetspolicyn",
        "faq_title": "Frågor",
        "faq": [
            ("Behöver jag ett konto?", "Nej. Ingen registrering och ingen inloggning. Köp går via ditt Google Play-konto."),
            ("Fungerar appen utan internet?", "Ja. Att läsa mönster och sticka kräver aldrig internet. Anslutning behövs bara för att köpa och ibland för att bekräfta prenumerationen."),
            ("Vilka enheter fungerar den på?", "Android 8.1 eller senare: telefoner, surfplattor och BOOX e-ink-plattor med Google Play."),
            ("Vilka mönster passar?", "PDF-mönster med ett diagram på ett rutnät. Testad på dussintals DROPS-diagram; appen hittar själv rutnätet och varven, och kanterna kan du justera för hand."),
            ("Vad kan jag göra utan att köpa?", "Lägga till projekt, öppna mönster, bläddra bland sidorna och markera diagram. Att sticka varv för varv med markerat varv kräver den gratis provperioden eller ett köp."),
            ("Jag har en ny telefon. Betalar jag igen?", "Nej. Installera Gabi Knits med samma Google-konto och tryck på ”Återställ köp”."),
            ("Hur säger jag upp prenumerationen?", "I Google Play: Betalningar och prenumerationer → Prenumerationer. Dina projekt stannar där de är."),
            ("Finns det en version för iPhone eller iPad?", "Inte än – Android kommer först."),
        ],
        "cta_title": "Frågor eller idéer?",
        "cta_text": "Skriv till Gabi – om ett mönster som inte fungerar, en idé till appen eller en fråga före lanseringen. Gabi läser varje meddelande.",
        "contact_title": "Kontakt",
        "contact_text": "Frågor, idéer, ett mönster som inte fungerar? Skriv till Gabi:",
        "get_title": "Sticka med Gabi Knits",
        "get_text": "14 dagar gratis, sedan väljer du en plan. Inget konto och ingen reklam.",
        "get_badge": "Ladda ned på Google Play",
        "get_contact": "Frågor? Skriv till Gabi:",
        "video_alt": "Katten Gabi med glasögon stickar i en fåtölj i en mysig garnbutik",
        "vat": "Momsreg.nr PL7321956817",
        "privacy": "Integritetspolicy",
    },
}
